expression     = sequenced
               ;

sequenced      = ternary, { ",", ternary }
               ;

ternary        = equality, { '?', expression, ':', expression }
               ;

equality       = comparison, { ( "!=" | "==" ), comparison }
               ;

comparison     = addition, { ( ">" | ">=" | "<" | "<=" ), addition }
               ;

addition       = multiplication, { ( "*" | "/" ), multiplication }
               ;

multiplication = unary, { ( "*" | "/" ), unary }
               ;

unary          = ( "-" | "!" ), unary
               | primary
               ;

primary        = NUMBER
               | STRING
               | "true"
               | "false"
               | "nil"
               ;
